config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/', to: 'posts#index'

  resources :posts, shallow: true do
    resources :comments
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments

    mount_uploader :cover, CoverUploader
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    has_many :posts
    has_many :comments

    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]
    before_action :set_post, only: [:new, :create, :edit, :update]

    # GET /comments
    def index
        @comments = Comment.all
    end

    # GET /comments/1
    def show
    end

    # GET /comments/new
    def new
        @comment = Comment.new
    end

    # GET /comments/1/edit
    def edit
    end

    # POST /comments
    def create
        @comment = @post.comments.new(comment_params)
        @comment.user = current_user
        @comment.publication_date = Time.current

        if @comment.save
            redirect_to @post, notice: 'Comment was successfully created.'
        else
            render :new
        end
    end

    # PATCH/PUT /comments/1
    def update
        if @comment.update(comment_params)
            redirect_to @comment, notice: 'Comment was successfully updated.'
        else
            render :edit
        end
    end

    # DELETE /comments/1
    def destroy
        @comment.destroy
        redirect_to @comment.post
    end
end

private

# Use callbacks to share common setup or constraints between actions.
def set_comment
    @comment = Comment.find(params[:id])
    @post = @comment.post
end

# Use callbacks to share common setup or constraints between actions.
def set_post
    @post = Post.find(params[:post_id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def comment_params
    params.require(:comment).permit(:body)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :authorize_post, only: [:edit, :update, :destroy]

    # GET /posts
    def index
        @posts = Post.all
    end

    # GET /posts/1
    def show
        @comment = Comment.new
        @comments = Comment.all
    end

    # GET /posts/new
    def new
        @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
        @post = Post.new(post_params)
        @post.user = current_user
        @post.publication_date = Time.current

        if @post.save
            redirect_to @post, notice: 'Post was successfully created.'
        else
            render :new
        end
    end

    # PATCH/PUT /posts/1
    def update
        if @post.update(post_params)
            redirect_to @post, notice: 'Post was successfully updated.'
        else
            render :edit
        end
    end

    # DELETE /posts/1
    def destroy
        @post.destroy

        redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:title, :extract, :body, :cover)
    end

    # Users cannot touch other users posts
    def authorize_post
        unless @post.user == current_user
            redirect_to posts_url, notice: 'You are not the owner of this post.'
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    def index
        @users = User.all
    end

    # GET /users/1
    def show
    end

    # GET /users/new
    def new
        @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to @user, notice: 'User was successfully created.'
        else
            render :new
        end
    end

    # PATCH/PUT /users/1
    def update
        if @user.update(user_params)
            redirect_to @user, notice: 'User was successfully updated.'
        else
            render :edit
        end
    end

    # DELETE /users/1
    def destroy
        @user.destroy

        redirect_to users_url, notice: 'User was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, comment]) do |form| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
                <% comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
    <thead>
    <tr>
        <th>Body</th>
        <th>User</th>
        <th>Post</th>
        <th>Publication date</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @comments.each do |comment| %>
        <tr>
            <td><%= comment.body %></td>
            <td><%= comment.user %></td>
            <td><%= comment.post %></td>
            <td><%= comment.publication_date %></td>
            <td><%= link_to 'Show', comment %></td>
            <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
            <td><%= link_to 'Destroy', comment, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', post_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Body:</strong>
    <%= @comment.body %>
</p>

<p>
    <strong>User:</strong>
    <%= @comment.user %>
</p>

<p>
    <strong>Post:</strong>
    <%= @comment.post %>
</p>

<p>
    <strong>Publication date:</strong>
    <%= @comment.publication_date %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RubyGdata</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag    'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="flex items-center justify-between flex-wrap bg-blue-500 p-6 shadow-lg mt-4 mb-16">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <span class="font-semibold text-xl tracking-tight ml-4">RuBYGdata</span>
    </div>
    <div class="block lg:hidden">
      <button
        class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
        </svg>
      </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
      <div class="text-sm lg:flex-grow">
        <%= link_to 'Posts', posts_path, class: "link text-white hover:border-white" %>
      </div>
      <div class="flex flex-row justify-around items-center">
        <% if user_signed_in? %>
        <span class="mr-4 text-white">
          Welcome, <%= current_user.first_name %>
        </span>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn bg-transparent hover:bg-white text-white hover:text-blue-500 hover:border-transparent" %>
        <% else %>
        <%= link_to 'Login', new_user_session_path, class:"btn bg-transparent hover:bg-white text-white hover:text-blue-500 hover:border-transparent" %>
        <% end %>
      </div>
    </div>
  </nav>
  </header>

  <main class="container mx-auto">
    <%= yield %>
  </main>

</body>

</html>

app/views/posts/_commentform.html.erb
<%= form_for([@post, comment]) do |form| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
                <% comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.text_area :body %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
                <% post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :extract %>
        <%= form.text_area :extract %>
    </div>

    <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <div class="field">
        <%= form.label :cover %>
        <%= form.file_field :cover %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="text-3xl font-bold mb-8">Editing Post</h1>

<section class="mb-16">
    <%= render 'form', post: @post %>
</section>

<section class="mb-8">
    <%= link_to 'Show', @post, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white ml-4' %>
    <%= link_to 'Back', posts_path, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white ml-4' %>
</section>

app/views/posts/index.html.erb
<% if notice %>
    <p id="notice" class="p-4"><%= notice %></p>
<% end %>

<% @posts.each do |post| %>
    <article class="rounded shadow-lg flex flex-row flex-wrap mb-16">
        <%= image_tag post.cover.thumb_square.url, class: 'object-cover object-center rounded-l w-full md:w-1/3', style: 'max-height:20rem' %>
        <div class="flex flex-col p-4 w-full md:w-2/3 justify-around">
            <div class="flex flex-row justify-between w-full mb-8">
                <h2 class="text-2xl font-bold inline-block"><%= link_to post.title, post, class: 'link text-blue-400 hover:border-blue-400' %></h2>
                <span class="p-4">by <%= link_to post.user.full_name, post.user, class: 'link text-blue-400 hover:border-blue-400' %>
                    on <%= post.publication_date.strftime("%m/%d/%Y %H:%M") %></span>
            </div>
            <p class="p-4"><%= post.extract %></p>
            <div class="flex flex-row justify-end">
                <%= link_to 'Read more', post, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white ml-4' %>
                <% if user_signed_in? && current_user.id == post.user.id %>
                    <span><%= link_to 'Edit', edit_post_path(post), class: 'btn border-orange-500 text-orange-500 hover:border-white hover:bg-orange-500 hover:text-white ml-4' %></span>
                    <span><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn border-red-500 text-red-500 hover:border-white hover:bg-red-500 hover:text-white ml-4' %></span>
                <% end %>
            </div>
        </div>
    </article>
<% end %>

<% if user_signed_in? %>
    <%= link_to 'Write a new post', new_post_path, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white' %>
<% end %>

app/views/posts/new.html.erb
<h1 class="text-3xl font-bold mb-8">New Post</h1>

<section class="mb-16">
    <%= render 'form', post: @post %>
</section>

<section class="mb-8">
    <%= link_to 'Back', posts_path, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white ml-4' %>
</section>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<article class="rounded shadow-lg flex flex-col mb-16">
    <div class="rounded w-full relative">
        <%= image_tag @post.cover.url, class: 'object-cover object-center rounded-t w-full', style: 'max-height:26rem; filter:brightness(50%)' %>
        <div class="absolute top-0 left-0 p-8">
            <h2 class="text-6xl font-bold text-white"><%= @post.title %></h2>
            <span class="p-4 text-white">by <%= link_to @post.user.full_name, @post.user, class: 'link text-blue-400 hover:border-blue-400' %>
                on <%= @post.publication_date.strftime("%m/%d/%Y %H:%M") %></span>
        </div>
    </div>
    <div class="flex flex-col w-full mb-8">
        <p class="p-8 mt-4 w-full overflow-hidden"><%= @post.body %></p>
    </div>
</article>

<section class="w-full mx-auto md:w-1/2 mb-16">
    <% @post.comments.each do |comment| %>
        <article class="flex flex-col rounded shadow-md bg-blue-100 mb-4">
            <div class="flex flex-row justify-between p-4 border-b border-blue-200">
                <h3 class="font-bold inline-block"><%= link_to comment.user.full_name, comment.user, class: 'link text-blue-400 hover:border-blue-400' %></h3>
                <span><%= comment.publication_date.strftime("%m/%d/%Y %H:%M") %></span>
            </div>
            <p class="p-4"><%= comment.body %></p>
            <% if user_signed_in? && current_user.id == comment.user.id %>
                <div class="text-right p-4">
                    <%= link_to 'Destroy', comment, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn ml-2' %>
                </div>
            <% end %>
        </article>
    <% end %>
</section>

<section class="mb-8 mx-auto w-full md:w-1/2">
    <% if user_signed_in? %>
        <h2 class="text-2xl font-bold px-4 mb-4">Post a comment...</h2>

        <%= render 'commentform', comment: @comment %>
    <% end %>
</section>

<section class="mb-8">
    <%= link_to 'Back', posts_path, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white ml-4' %>
    <% if user_signed_in? && current_user.id == @post.user.id %>
        <%= link_to 'Edit', edit_post_path(@post), class: 'btn border-orange-500 text-orange-500 hover:border-white hover:bg-orange-500 hover:text-white ml-4' %>
    <% end %>
</section>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :first_name %>
        <%= form.text_field :first_name %>
    </div>

    <div class="field">
        <%= form.label :last_name %>
        <%= form.text_field :last_name %>
    </div>

    <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
    <thead>
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="text-3xl font-bold">
    <% if user_signed_in? && current_user.id == @user.id %>
        My profile
    <% else %>
        <%= @user.full_name %>
    <% end %>
</h2>
<span class="block mb-8"><%= @user.email %></span>


<h3 class="text-2xl font-bold mb-4">Latest posts</h3>

<section class="w-full mb-16">
    <% @user.posts.order(publication_date: :desc).each do |post| %>
        <article class="rounded shadow-lg flex flex-row flex-wrap mb-16">
            <%= image_tag post.cover.url, class: 'object-cover object-center rounded-l w-full md:w-1/3', style: 'max-height:20rem' %>
            <div class="flex flex-col p-4 w-full md:w-2/3 justify-around">
                <div class="flex flex-row justify-between w-full mb-8">
                    <h2 class="text-2xl font-bold inline-block"><%= link_to post.title, post, class: 'link text-blue-400 hover:border-blue-400' %></h2>
                    <span class="p-4">by <%= link_to post.user.full_name, post.user, class: 'link text-blue-400 hover:border-blue-400' %>
                        on <%= post.publication_date.strftime("%m/%d/%Y %H:%M") %></span>
                </div>
                <p class="p-4"><%= post.extract %></p>
                <div class="flex flex-row justify-end">
                    <%= link_to 'Read more', post, class: 'btn border-blue-500 text-blue-500 hover:border-white hover:bg-blue-500 hover:text-white ml-4' %>
                    <% if user_signed_in? && current_user.id == post.user.id %>
                        <span><%= link_to 'Edit', edit_post_path(post), class: 'btn border-orange-500 text-orange-500 hover:border-white hover:bg-orange-500 hover:text-white ml-4' %></span>
                        <span><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn border-red-500 text-red-500 hover:border-white hover:bg-red-500 hover:text-white ml-4' %></span>
                    <% end %>
                </div>
            </div>
        </article>
    <% end %>
</section>

<h3 class="text-2xl font-bold mb-4">Latest comments</h3>

<section class="w-full mx-auto md:w-1/2 mb-16">
    <% @user.comments.order(publication_date: :desc).each do |comment| %>
        <article class="flex flex-col rounded shadow-md bg-blue-100 mb-4">
            <div class="flex flex-row justify-between p-4 border-b border-blue-200">
                <h3 class="font-bold inline-block"><%= link_to comment.user.full_name, comment.user, class: 'link text-blue-400 hover:border-blue-400' %></h3>
                <span><%= comment.publication_date.strftime("%m/%d/%Y %H:%M") %></span>
            </div>
            <p class="p-4"><%= comment.body %></p>
            <% if user_signed_in? && current_user.id == comment.user.id %>
                <div class="text-right p-4">
                    <%= link_to 'Destroy', comment, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn ml-2' %>
                </div>
            <% end %>
        </article>
    <% end %>
</section>